name: YANA Resource Model Source
version: 1.1
rundeckPluginVersion: 1.0
author: alexh
date: 5/10/12
providers:
    - name: yana-nodes
      service: ResourceModelSource
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: nodes.sh
      title: YANA Resource Model Source
      description: Get node data from YANA
      resource-format: resourcexml
      config:
        - type: String
          name: nodetype
          title: Node Type
          description: The NodeType to search
          default: Host
        - type: String
          name: project
          title: Project 
          description: The YANA project name
        - type: String
          name: url
          title: URL
          description: The node authority URL
          default: ''
        - type: String
          name: username
          title: Username
          description: The Yana username
        - type: String
          name: password
          title: Password
          description: The Yana password




